Imports Microsoft.VisualBasic
Imports System
Imports System.Collections.Generic
Imports System.Text
Imports System.Drawing

Namespace DevExpress.VideoRent.Win
	Public Class ConstStrings
		Public Const AboutGroup As String = "About"
		Public Const RentalGroup As String = "Movie Rental"
		Public Const CatalogGroup As String = "Catalog"
		Public Const KPIGroup As String = "KPI"
		Public Const StatisticsGroup As String = "Statistics"
		Public Const ReportsGroup As String = "Reports"
		Public Const AdminGroup As String = "Administrator"
		Public Const EmployeesModule As String = "Employees"
		Public Const RentModule As String = "Movie Rentals" & Constants.vbCrLf & "(for current customer)"
		Public Const CustomersModule As String = "Customers"
		Public Const MoviesModule As String = "Movies"
		Public Const ActorsModule As String = "Actors/Crew"
		Public Const CompaniesModule As String = "Companies"
		Public Const MoviesKPIModule As String = "Movies KPI"
		Public Const CustomersKPIModule As String = "Customers KPI"
		Public Const CustomersDatesModule As String = "Customers by Dates"
		Public Const Revenue12MonthsModule As String = "Revenue - Last 12 Months"
		Public Const RevenueSplitModule As String = "Revenue Categories – Last 12 Months"
		Public Const TopCustomersModule As String = "Top Customers"
		Public Const CustomerRevenueModule As String = "Revenue by Customers"
		Public Const MediaPerformanceModule As String = "Performance by Media Type"
		Public Const RentScheduleModule As String = "Rental Calendar" & Constants.vbCrLf & "(by customer)"

		Public Const ActiveGrid_Warning As String = "This operation might take a few minutes." & Constants.vbCrLf & "Do you want to continue?"
		Public Const RuleIsNotBlankWarning As String = "This value cannot be empty"
		Public Const RuleGreaterOrEqualZeroWarning As String = "This value cannot be negative"
		Public Const RuleUniqueName As String = "Name must be unique"
		Public Const CloseCancelFormWarning As String = "Do you want to save changes?"
		Public Const CloseCancelFormsWarning As String = "Some detail forms have been modified." & Constants.vbCrLf & "Do you want to close these forms?"
		Public Const DeleteRecord As String = "Do you want to delete the {0}?"
		Public Const PhotoOf As String = "Photo: {0} of {1}"
		Public Const CannotDeleteCustomer As String = "Cannot delete customer {0}. The 'Rental' table contains linked records."
		Public Const EditViewOptions As String = "Modify {0} List View settings"

		Public Const AutoFilterRowHint As String = "To quickly locate a customer, type the customer's name or a part of his/her name in the Name column in the top row. You can also search against other columns in the same way."
		Public Const FindCustomerHint As String = "Please choose a customer"
		Public Const NewRecordsIDString As String = "<unassigned>"

		Public Const ReturnAndPaymentLateFeeQuestion As String = "Return items and display payment receipt?"
		Public Const ReturnQuestion As String = "Return items?"

		Public Const Question As String = "Question"
		Public Const Warning As String = "Warning"
		Public Const [Error] As String = "Error"
		Public Const Export As String = "Export"
		Public Const Information As String = "Information"
		Public Const AdvancedGrid As String = "Advanced grid"
		Public Const SimpleGrid As String = "Simple grid"
		Public Const Grid As String = "Grid"
		Public Const Cards As String = "Cards"
		Public Const UnableOpenDb As String = "Unable to open the database. A new database will be created."
        Public Const UnableCreateDb As String = "Unable to create a database. Please check the connection settings."
        Public Const ObjectCanNotBeDeleted As String = "This object cannot be deleted."
		Public Const NotAllItemsCanBeDeleted As String = "Some of items cannot be deleted. Do you want to continue?"
		Public Const ExportFileOpen As String = "Do you want to open this file?"
        Public Const ExportError As String = "An error occurred while exporting"
		Public Const DateLess As String = "End Date is less than Start Date"

		Public Const ExportDescription As String = "Export data into different file formats"
		Public Const PrintPreviewDescription As String = "Preview a report..."
		Public Const LayoutOptionDescription As String = "Customize layout options..."
		Public Const PeriodDescription As String = "Specify data processing date intervals..."
		Public Const AboutDescription As String = "About this application..."
		Public Const ChooseSkinDescription As String = "Specify the application’s paint scheme"

		Public Const DatabaseCreating As String = "To run the application, a sample database needs to be created and populated with data." & Constants.vbCrLf & "Please select the database type and connection options below."
		Public Const CustomerDetailTooltip As String = "Double click here to show the current customer details"
		Public Const CurrentCustomer As String = "Current customer: {0}"
		Public Const [Nothing] As String = "nothing"
        Public Const DemoName As String = "Video Rental Demo (Visual Basic)"
		Public Const DefaultPageName As String = "Home"
		Public Const AddButtonHint As String = "Add a new {0} record"
		Public Const EditButtonHint As String = "Edit the highlighted {0} record"
		Public Const DeleteButtonHint As String = "Delete the highlighted {0} record"
		Public Const RefreshButtonHint As String = "Refresh the {0} List View"
		Public Const RefreshDefaultButtonHint As String = "Refresh data"
		Public Const PrevButtonHint As String = "Previous {0} record"
		Public Const NextButtonHint As String = "Next {0} record"
		Public Const PrintPreviewButtonHint As String = "Generate {1} {0} report"
		Public Const ExportButtonHint As String = "Export {0} report"
		Public Const PrintPreviewButtonHintDefault As String = "Preview the report"
		Public Const ExportButtonHintDefault As String = "Export the report"
		Public Const HomeButtonHint As String = "Return to {0} List View"
		Public Const PDFOpenFileFilter As String = "PDF document (*.pdf)|*.pdf"
		Public Const HTMLOpenFileFilter As String = "HTML document (*.html)|*.html"
		Public Const MHTOpenFileFilter As String = "MHT document (*.mht)|*.mht"
		Public Const XLSOpenFileFilter As String = "XLS document (*.xls)|*.xls"
		Public Const PNGOpenFileFilter As String = "PNG image (*.png)|*.png"
		Public Const CustomerDiscountLevelToolTip As String = "<b>{0}</b>" & Constants.vbCrLf & "Discount: <b>{1:p}</b>" & Constants.vbCrLf & "Total Amount: <b>$ {2}</b>"

		Public Const NewActor As String = "New Actor"
		Public Const NewCompany As String = "New Company"
		Public Const NewCustomer As String = "New Customer"
		Public Const NewMovie As String = "New Movie"
		Public Const NewCategory As String = "New Category"

		Public Const Customer As String = "Customer"
		Public Const Artist As String = "Actor/Crew"
		Public Const Company As String = "Company"
		Public Const Movie As String = "Movie"
		Public Const Receipt As String = "Receipt"

		Public Const Customers As String = "Customers"
		Public Const Artists As String = "Actors/Crew"
		Public Const Companies As String = "Companies"
		Public Const Movies As String = "Movies"
		Public Const Receipts As String = "Receipts"

		Public Const Photo As String = "photo"
		Public Const Screens As String = "Photo Gallery"
		Public Const Revenue As String = "Revenue"
		Public Const ReceiptCount As String = "Receipt Count"
		Public Const Revenue12Months As String = "Revenue - Last 12 Months"
		Public Const ReceiptCount12Months As String = "Receipt Count - Last 12 Months"
		Public Const NullString As String = "(null)"
		Public Const TimePeriod As String = "Time Period ({0:d} - {1:d})"
		Public Const ComparePeriod As String = "Period Comparison ({0:d} - {1:d})"
		Public Const MovieRevenues As String = "{0} Movie Revenues"
		Public Const MostRentedMovies As String = "The Most Rented Movies on {0}"
		Public Const Total As String = "Total"
		Public Const TopCustomer As String = "Top Customer"
		Public Const RevenueDifference As String = "Revenue Difference"
		Public Const MovieRating As String = "Movie Rating"
		Public Const RentType As String = "Rental type"
		Public Const SubclassError As String = "Class has to be inherited from Form"
		Public Const PublicConstructorError As String = "{0} doesn't have public constructor with empty parameters"
		Public Const LookupDetails As String = "Lookup details..."
		Public Const DatePeriodCaption As String = "From {0:d} to {1:d}"
		Public Const ViewOptions As String = "List View Options"
		Public Const ReceiptsViewOptions As String = "Receipts View Options"
		Public Const AddMovieTo As String = "{0} - Link Movie"
		Public Const AddArtistTo As String = "{0} - Add Actors/Crew"
		Public Const AddCompanyTo As String = "{0} - Add Company"
		Public Const ShowReportDesigner As String = "Show Report Designer"
		Public Const AllFormats As String = "All Formats"
		Public Const ItemsCountHtmlCaption As String = "Totals: <b>{0}</b>."
		Public Const ItemsCountDetailHtmlCaption As String = "<b>{0}</b> currently rented, <b>{1}</b> available for rent, <b>{2}</b> available for sale, <b>{3}</b> lost, <b>{4}</b> damaged, <b>{5}</b> sold."
		Public Const ExpectedOn As String = "Expected On"
		Public Const ReturnedOn As String = "Returned On"
		Public Const AboutFormVersion As String = "for WinForms " & AssemblyInfo.MarketingVersion
		Public Const AboutFormCopyright As String = AssemblyInfo.AssemblyCopyright & " All rights reserved."
		Public Const AboutFormDescription As String = "This application demonstrates some of the capabilities available to you when using DevExpress WinForms Controls and Libraries. To learn more about DevExpress and download your free evaluation, use the links below."
		Public Const AboutFormLink1 As String = "DevExpress.com"
		Public Const AboutFormLink2 As String = "Download Free Trials"
		Public Const AboutFormLink3 As String = "Purchase DevExpress Products"
		Public Const AboutFormSeparator As String = "   |   "
		Public Const WelcomeText1 As String = "About this Application"
		Public Const WelcomeText2 As String = "This sample WinForms application illustrates some of the capabilities available to you when using award-winning DevExpress WinForms Control Libraries."
		Public Const WelcomeText3 As String = "Controls used in this demo are:"
		Public Const WelcomeText4 As String = "Press 'F1' to return again to this page"
		Public Const WelcomeLink1 As String = "Learn More"
		Public Const WelcomeLink2 As String = "Download Trial"
		Public Const WelcomeLink3 As String = "Buy Now"
		Public Const PriceError As String = "Must specify Price before saving the record."
		Public Const MovieList As String = "Movie List"
		Public Const CustomerList As String = "Customer List"
		Public Const ArtistList As String = "Actors/Crew List"
		Public Const CompanyList As String = "Company List"
		Public Const MovieItemStatusActive As String = "Available for Rent"
		Public Const NoImageData As String = "No image for current record"
		Public Const RenterDiscount As String = "{0} Renter"
		Public Const DiscountNote As String = "These are auto-calculated values and are based on rental volume."
		Public Const PaletteButtonHint As String = "Specify a color palette ({0})"
		Public Const ReadOnlyCaption As String = "{0} (Read Only)"

        Public Const DXLink As String = "www.devexpress.com"
        Public Const TrialsLink As String = AssemblyInfo.DXLinkTrial
        Public Const PurchaseLink As String = AssemblyInfo.DXLinkBuyNow
	End Class
End Namespace
