<%@ Page Title="" Language="C#" MasterPageFile="~/Site.master" AutoEventWireup="true" CodeFile="Products.aspx.cs" Inherits="Products" %>
<asp:Content ID="Content4" ContentPlaceHolderID="MainContentPlaceHolder" runat="Server">
    <dx:Products_Master ID="Products_Master" runat="server" />
    <dx:ASPxCallbackPanel ID="DetailsCallbackPanel" ClientInstanceName="detailsCallbackPanel" runat="server" CssClass="productsDetailsPanel" Width="100%" EnableViewState="false" Collapsible="true">
        <SettingsAdaptivity CollapseAtWindowInnerHeight="700" />
        <SettingsCollapsing ExpandEffect="PopupToTop" ExpandButton-Position="Far" AnimationType="Slide" />
        <Styles>
            <ExpandBar Width="100%"></ExpandBar>
            <ExpandedPanel CssClass="expanded"></ExpandedPanel>
        </Styles>
        <PanelCollection>
            <dx:PanelContent>
                <dx:Products_Detail ID="Products_Detail" runat="server" />
            </dx:PanelContent>
        </PanelCollection>
    </dx:ASPxCallbackPanel>
    <dx:ASPxPopupControl runat="server" ID="ProductPopup" ClientInstanceName="productPopup" ShowHeader="false" CloseAction="OuterMouseClick" PopupAnimationType="Fade" CloseOnEscape="true"
        Modal="true" PopupVerticalAlign="WindowCenter" PopupHorizontalAlign="WindowCenter" Width="850" Height="700" OnWindowCallback="ProductPopup_WindowCallback">
        <ContentCollection>
            <dx:PopupControlContentControl>
                <dx:ASPxImageSlider ID="ProductPopupImageSlider" runat="server">
                    <Styles>
                        <ImageArea Width="800" Height="600" />
                    </Styles>
                    <SettingsAutoGeneratedImages ImageCacheFolder="~\Thumb\" />
                </dx:ASPxImageSlider>
            </dx:PopupControlContentControl>
        </ContentCollection>
    </dx:ASPxPopupControl>
    <dx:RevenueAnalysisPopup ID="RevenueAnalysisPopup" runat="server" />
</asp:Content>
