'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
	Imports System
Namespace My


	''' <summary>
	'''   A strongly-typed resource class, for looking up localized strings, etc.
	''' </summary>
	' This class was auto-generated by the StronglyTypedResourceBuilder
	' class via a tool like ResGen or Visual Studio.
	' To add or remove a member, edit your .ResX file then rerun ResGen
	' with the /str option, or rebuild your VS project.
	<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()> _
	Friend Class Resources

		Private Shared resourceMan As Global.System.Resources.ResourceManager

		Private Shared resourceCulture As Global.System.Globalization.CultureInfo

		<Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")> _
		Friend Sub New()
		End Sub

		''' <summary>
		'''   Returns the cached ResourceManager instance used by this class.
		''' </summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
		Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
			Get
				If Object.ReferenceEquals(resourceMan, Nothing) Then
					Dim temp As New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
					resourceMan = temp
				End If
				Return resourceMan
			End Get
		End Property

		''' <summary>
		'''   Overrides the current thread's CurrentUICulture property for all
		'''   resource lookups using this strongly typed resource class.
		''' </summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
		Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
			Get
				Return resourceCulture
			End Get
			Set(ByVal value As System.Globalization.CultureInfo)
				resourceCulture = value
			End Set
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property AnnotationMaximum() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("AnnotationMaximum", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property AnnotationMinimum() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("AnnotationMinimum", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property Appearance_16x16() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Appearance_16x16", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property Appearance_32x32() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Appearance_32x32", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property Bug() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Bug", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Byte[].
		''' </summary>
		Friend Shared ReadOnly Property CrossCursor() As Byte()
			Get
				Dim obj As Object = ResourceManager.GetObject("CrossCursor", resourceCulture)
				Return (CType(obj, Byte()))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property Mars() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Mars", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property NoBug() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("NoBug", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property Palette_16x16() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Palette_16x16", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property Palette_32x32() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Palette_32x32", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property Wizard_16x16() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Wizard_16x16", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property Wizard_32x32() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Wizard_32x32", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property
	End Class
End Namespace
