//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExpress.Xpo.Demos.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevExpress.Xpo.Demos.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon AppIcon {
            get {
                object obj = ResourceManager.GetObject("AppIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below is the Customer object loaded twice in two separate Units of Work..
        /// </summary>
        internal static string ModifiedPropertiesMessagesN1 {
            get {
                return ResourceManager.GetString("ModifiedPropertiesMessagesN1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ‘CompanyName’ property value is modified in the first Unit of Work and the ‘Phone’ – in the second..
        /// </summary>
        internal static string ModifiedPropertiesMessagesN2 {
            get {
                return ResourceManager.GetString("ModifiedPropertiesMessagesN2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The second Unit of Work is committed to the database. In the first Unit of Work, Customer is reloaded with merging its current changes with changes from the database. As the result, the &apos;Phone&apos; property values are the same in both Units of Work..
        /// </summary>
        internal static string ModifiedPropertiesMessagesN3 {
            get {
                return ResourceManager.GetString("ModifiedPropertiesMessagesN3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;CompanyName&apos; property value is modified in both Units of Work..
        /// </summary>
        internal static string ModifiedPropertiesMessagesN4 {
            get {
                return ResourceManager.GetString("ModifiedPropertiesMessagesN4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The changes in the second Unit of Work are committed to the database. The LockingException is thrown when the Customer reload occurs in the first Unit of Work, because of the merge collision..
        /// </summary>
        internal static string ModifiedPropertiesMessagesN5 {
            get {
                return ResourceManager.GetString("ModifiedPropertiesMessagesN5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The modified property value is reset and the Customer is successfully reloaded in the first Unit of Work..
        /// </summary>
        internal static string ModifiedPropertiesMessagesN6 {
            get {
                return ResourceManager.GetString("ModifiedPropertiesMessagesN6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ShowCode_32x32 {
            get {
                object obj = ResourceManager.GetObject("ShowCode_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Wizard_16x16 {
            get {
                object obj = ResourceManager.GetObject("Wizard_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Wizard_32x32 {
            get {
                object obj = ResourceManager.GetObject("Wizard_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Xpo_LargeIcon {
            get {
                object obj = ResourceManager.GetObject("Xpo_LargeIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
