Imports System
Imports System.Collections.Generic
Imports System.Linq
Imports System.Text
Imports System.Windows
Imports System.Windows.Controls
Imports System.Windows.Data
Imports System.Windows.Documents
Imports System.Windows.Input
Imports System.Windows.Media
Imports System.Windows.Media.Imaging
Imports System.Windows.Navigation
Imports System.Windows.Shapes
Imports DevExpress.Xpf.Grid
Imports DevExpress.Data
Imports DevExpress.Xpf.DemoBase
Imports DevExpress.Xpf.Editors.Settings
Imports System.Globalization
Imports DevExpress.Xpf.Editors
Imports DevExpress.XtraExport.Helpers
Imports DevExpress.Xpf.Grid.Printing

Namespace GridDemo
    <CodeFile("Controls/SalesByYearData.cs")>
    Partial Public Class FixedBands
        Inherits GridDemoModule

        Protected Overrides ReadOnly Property AllowWYSIWYGExport() As Boolean
            Get
                Return False
            End Get
        End Property

        Public Sub New()
            InitializeComponent()
        End Sub

        Protected Overrides Function GetReportView() As IGridViewFactory(Of ColumnWrapper, RowBaseWrapper)
            Return Nothing
        End Function

        Private Sub grid_AutoGeneratedColumns(ByVal sender As Object, ByVal e As RoutedEventArgs)
            grid.Bands(0).Fixed = FixedStyle.Left
            grid.Bands(0).OverlayHeaderByChildren = True
            Dim band As New GridControlBand() With {.Header = "Total", .Fixed = FixedStyle.Right, .OverlayHeaderByChildren = True}
            band.Columns.Add(New GridColumn() With {.FieldName = "Total", .UnboundType = UnboundColumnType.Decimal, .ReadOnly = True})
            grid.Bands.Add(band)

            grid.BeginDataUpdate()
            Dim editSettings As New SpinEditSettings() With {.MaskType = MaskType.Numeric, .Mask = "c", .MaskCulture = New CultureInfo("en-US"), .MaskUseAsDisplayFormat = True, .HorizontalContentAlignment = EditSettingsHorizontalAlignment.Right}
            For Each column As GridColumn In grid.Columns
                If column.FieldName <> "Employee" Then
                    grid.TotalSummary.Add(New GridSummaryItem() With {.FieldName = column.FieldName, .SummaryType = SummaryItemType.Sum})
                    column.EditSettings = editSettings
                End If
            Next column
            grid.EndDataUpdate()
        End Sub

        Private Sub grid_CustomUnboundColumnData(ByVal sender As Object, ByVal e As GridColumnDataEventArgs)
            Dim sum As Integer = 0
            For Each column As GridColumn In grid.Columns
                If column.FieldName <> "Employee" AndAlso column.FieldName <> "Total" Then
                    sum += CInt((e.GetListSourceFieldValue(column.FieldName)))
                End If
            Next column
            e.Value = sum
        End Sub
    End Class
End Namespace
