Imports DevExpress.Utils
Imports DevExpress.Xpf.DemoBase.DemoTesting
Imports DevExpress.Xpf.Printing
Imports System

Namespace ReportWpfDemo.Tests
    Friend NotInheritable Class DocumentPagesReadyConditionFactory

        Private Sub New()
        End Sub

        ' InstantVB 2.7 can't automatically resolve return value type of anonymous delegate or lambda.
        ' We use ConditionAdapter so that autogenerated VB code doesn't have warnings 'convert Object to boolean'
        Private Class ConditionAdapter
            Private Const sufficientPageCount As Integer = 10
            Private ReadOnly fixture As BaseDemoTestingFixture

            Public Sub New(ByVal fixture As BaseDemoTestingFixture)
                Guard.ArgumentNotNull(fixture, "fixture")
                Me.fixture = fixture
            End Sub

            Public Function EvaluateCondition() As Boolean
                If fixture.DemoBaseTesting.CurrentDemoModule Is Nothing Then
                    Return False
                End If
                Dim preview = BaseTestingFixture.HelperActions.FindElementByType(Of DocumentPreviewControl)(fixture.DemoBaseTesting.CurrentDemoModule)
                Return preview IsNot Nothing AndAlso (preview.PageCount > sufficientPageCount OrElse (preview.PageCount > 0 AndAlso preview.Document.IsCreating = False))
            End Function
        End Class

        ''' <summary>
        ''' Creates new instance of Condition that resolves to 'true' when document build is complete or sufficient page count was achieved.
        ''' </summary>
        ''' <param name="fixture"></param>
        ''' <returns></returns>
        Public Shared Function Create(ByVal fixture As BaseDemoTestingFixture) As Func(Of Boolean)
            Dim conditionAdapter As New ConditionAdapter(fixture)
            Return Function() conditionAdapter.EvaluateCondition()
        End Function
    End Class
End Namespace
