<%@ Page Language="C#" AutoEventWireup="true" CodeFile="SpreadsheetEdit.aspx.cs" Inherits="SpreadsheetEdit" MasterPageFile="~/DocumentEditor.master" %>
<asp:Content ID="Content1" runat="server" ContentPlaceHolderID="HeaderHolder">
</asp:Content>
<asp:Content ID="Content2" runat="server" ContentPlaceHolderID="ContentHolder">
    <dx:ASPxRibbon ID="DocumentRibbon" runat="server" ShowFileTab="false" Theme="MetropolisBlue" CssClass="DocumentRibbon">
        <Tabs>
            <dx:SRHomeTab>
                <Groups>
                    <dx:SRFileCommonGroup>
                        <Items>
                            <dx:RibbonButtonItem Name="NewButton" Size="Small" Text="New Document">
                                <SmallImage IconID="actions_new_16x16gray" />
                            </dx:RibbonButtonItem>
                            <dx:RibbonButtonItem Name="SaveAsButton" Size="Small" Text="Save As Document">
                                <SmallImage IconID="save_saveas_16x16gray" />
                            </dx:RibbonButtonItem>
                            <dx:SRFilePrintCommand Size="Small" Text="Print Document">
                            </dx:SRFilePrintCommand>
                        </Items>
                    </dx:SRFileCommonGroup>
                    <dx:SRUndoGroup>
                        <Items>
                            <dx:SRFileUndoCommand Size="Large">
                            </dx:SRFileUndoCommand>
                            <dx:SRFileRedoCommand Size="Large">
                            </dx:SRFileRedoCommand>
                        </Items>
                    </dx:SRUndoGroup>
                    <dx:SRClipboardGroup>
                        <Items>
                            <dx:SRPasteSelectionCommand>
                            </dx:SRPasteSelectionCommand>
                            <dx:SRCutSelectionCommand>
                            </dx:SRCutSelectionCommand>
                            <dx:SRCopySelectionCommand>
                            </dx:SRCopySelectionCommand>
                        </Items>
                    </dx:SRClipboardGroup>
                    <dx:SRFontGroup>
                        <Items>
                            <dx:SRFormatFontNameCommand>
                                <PropertiesComboBox NullText="(Font Name)" Width="130px">
                                </PropertiesComboBox>
                            </dx:SRFormatFontNameCommand>
                            <dx:SRFormatFontSizeCommand>
                                <PropertiesComboBox NullText="(Font Size)" Width="60px">
                                </PropertiesComboBox>
                            </dx:SRFormatFontSizeCommand>
                            <dx:SRFormatIncreaseFontSizeCommand>
                            </dx:SRFormatIncreaseFontSizeCommand>
                            <dx:SRFormatDecreaseFontSizeCommand>
                            </dx:SRFormatDecreaseFontSizeCommand>
                            <dx:SRFormatFontBoldCommand>
                            </dx:SRFormatFontBoldCommand>
                            <dx:SRFormatFontItalicCommand>
                            </dx:SRFormatFontItalicCommand>
                            <dx:SRFormatFontUnderlineCommand>
                            </dx:SRFormatFontUnderlineCommand>
                            <dx:SRFormatFontStrikeoutCommand>
                            </dx:SRFormatFontStrikeoutCommand>
                            <dx:SRFormatBordersCommand>
                            </dx:SRFormatBordersCommand>
                            <dx:SRFormatFillColorCommand AutomaticColorItemValue="Automatic">
                            </dx:SRFormatFillColorCommand>
                            <dx:SRFormatFontColorCommand AutomaticColorItemValue="Automatic">
                            </dx:SRFormatFontColorCommand>
                            <dx:SRFormatBorderLineColorCommand AutomaticColorItemValue="Automatic">
                            </dx:SRFormatBorderLineColorCommand>
                        </Items>
                    </dx:SRFontGroup>
                    <dx:SRAlignmentGroup>
                        <Items>
                            <dx:SRFormatAlignmentTopCommand>
                            </dx:SRFormatAlignmentTopCommand>
                            <dx:SRFormatAlignmentMiddleCommand>
                            </dx:SRFormatAlignmentMiddleCommand>
                            <dx:SRFormatAlignmentBottomCommand>
                            </dx:SRFormatAlignmentBottomCommand>
                            <dx:SRFormatAlignmentLeftCommand>
                            </dx:SRFormatAlignmentLeftCommand>
                            <dx:SRFormatAlignmentCenterCommand>
                            </dx:SRFormatAlignmentCenterCommand>
                            <dx:SRFormatAlignmentRightCommand>
                            </dx:SRFormatAlignmentRightCommand>
                            <dx:SRFormatDecreaseIndentCommand>
                            </dx:SRFormatDecreaseIndentCommand>
                            <dx:SRFormatIncreaseIndentCommand>
                            </dx:SRFormatIncreaseIndentCommand>
                            <dx:SRFormatWrapTextCommand>
                            </dx:SRFormatWrapTextCommand>
                            <dx:SREditingMergeCellsGroupCommand>
                            </dx:SREditingMergeCellsGroupCommand>
                        </Items>
                    </dx:SRAlignmentGroup>
                    <dx:SRNumberGroup>
                        <Items>
                            <dx:SRFormatNumberAccountingCommand>
                            </dx:SRFormatNumberAccountingCommand>
                            <dx:SRFormatNumberPercentCommand>
                            </dx:SRFormatNumberPercentCommand>
                            <dx:SRFormatNumberCommaStyleCommand>
                            </dx:SRFormatNumberCommaStyleCommand>
                            <dx:SRFormatNumberIncreaseDecimalCommand>
                            </dx:SRFormatNumberIncreaseDecimalCommand>
                            <dx:SRFormatNumberDecreaseDecimalCommand>
                            </dx:SRFormatNumberDecreaseDecimalCommand>
                        </Items>
                    </dx:SRNumberGroup>
                    <dx:SRCellsGroup>
                        <Items>
                            <dx:SRFormatInsertCommand>
                            </dx:SRFormatInsertCommand>
                            <dx:SRFormatRemoveCommand>
                            </dx:SRFormatRemoveCommand>
                            <dx:SRFormatFormatCommand>
                            </dx:SRFormatFormatCommand>
                        </Items>
                    </dx:SRCellsGroup>
                    <dx:SREditingGroup>
                        <Items>
                            <dx:SRFormatAutoSumCommand>
                            </dx:SRFormatAutoSumCommand>
                            <dx:SRFormatFillCommand>
                            </dx:SRFormatFillCommand>
                            <dx:SRFormatClearCommand>
                            </dx:SRFormatClearCommand>
                            <dx:SREditingSortAndFilterCommand>
                            </dx:SREditingSortAndFilterCommand>
                            <dx:SREditingFindAndSelectCommand>
                            </dx:SREditingFindAndSelectCommand>
                        </Items>
                    </dx:SREditingGroup>
                    <dx:SRStylesGroup>
                        <Items>
                            <dx:SRFormatAsTableCommand>
                            </dx:SRFormatAsTableCommand>
                        </Items>
                    </dx:SRStylesGroup>
                </Groups>
            </dx:SRHomeTab>
            <dx:SRInsertTab>
                <Groups>
                    <dx:SRTablesGroup>
                        <Items>
                            <dx:SRInsertTableCommand>
                            </dx:SRInsertTableCommand>
                        </Items>
                    </dx:SRTablesGroup>
                    <dx:SRIllustrationsGroup>
                        <Items>
                            <dx:SRFormatInsertPictureCommand>
                            </dx:SRFormatInsertPictureCommand>
                        </Items>
                    </dx:SRIllustrationsGroup>
                    <dx:SRChartsGroup>
                        <Items>
                            <dx:SRInsertChartColumnCommand>
                            </dx:SRInsertChartColumnCommand>
                            <dx:SRInsertChartLinesCommand>
                            </dx:SRInsertChartLinesCommand>
                            <dx:SRInsertChartPiesCommand>
                            </dx:SRInsertChartPiesCommand>
                            <dx:SRInsertChartBarsCommand>
                            </dx:SRInsertChartBarsCommand>
                            <dx:SRInsertChartAreasCommand>
                            </dx:SRInsertChartAreasCommand>
                            <dx:SRInsertChartScattersCommand>
                            </dx:SRInsertChartScattersCommand>
                            <dx:SRInsertChartOthersCommand>
                            </dx:SRInsertChartOthersCommand>
                        </Items>
                    </dx:SRChartsGroup>
                    <dx:SRLinksGroup>
                        <Items>
                            <dx:SRFormatInsertHyperlinkCommand>
                            </dx:SRFormatInsertHyperlinkCommand>
                        </Items>
                    </dx:SRLinksGroup>
                </Groups>
            </dx:SRInsertTab>
            <dx:SRPageLayoutTab>
                <Groups>
                    <dx:SRPageSetupGroup ShowDialogBoxLauncher="True">
                        <Items>
                            <dx:SRPageSetupMarginsCommand>
                            </dx:SRPageSetupMarginsCommand>
                            <dx:SRPageSetupOrientationCommand>
                            </dx:SRPageSetupOrientationCommand>
                            <dx:SRPageSetupPaperKindCommand>
                            </dx:SRPageSetupPaperKindCommand>
                        </Items>
                    </dx:SRPageSetupGroup>
                    <dx:SRPrintGroup ShowDialogBoxLauncher="True">
                        <Items>
                            <dx:SRPrintGridlinesCommand>
                            </dx:SRPrintGridlinesCommand>
                            <dx:SRPrintHeadingsCommand>
                            </dx:SRPrintHeadingsCommand>
                        </Items>
                    </dx:SRPrintGroup>
                </Groups>
            </dx:SRPageLayoutTab>
            <dx:SRFormulasTab>
                <Groups>
                    <dx:SRFunctionLibraryGroup>
                        <Items>
                            <dx:SRFunctionsAutoSumCommand>
                            </dx:SRFunctionsAutoSumCommand>
                            <dx:SRFunctionsFinancialCommand>
                            </dx:SRFunctionsFinancialCommand>
                            <dx:SRFunctionsLogicalCommand>
                            </dx:SRFunctionsLogicalCommand>
                            <dx:SRFunctionsTextCommand>
                            </dx:SRFunctionsTextCommand>
                            <dx:SRFunctionsDateAndTimeCommand>
                            </dx:SRFunctionsDateAndTimeCommand>
                            <dx:SRFunctionsLookupAndReferenceCommand>
                            </dx:SRFunctionsLookupAndReferenceCommand>
                            <dx:SRFunctionsMathAndTrigonometryCommand>
                            </dx:SRFunctionsMathAndTrigonometryCommand>
                            <dx:SRFunctionsMoreCommand>
                            </dx:SRFunctionsMoreCommand>
                        </Items>
                    </dx:SRFunctionLibraryGroup>
                    <dx:SRCalculationGroup>
                        <Items>
                            <dx:SRFunctionsCalculationOptionCommand>
                            </dx:SRFunctionsCalculationOptionCommand>
                            <dx:SRFunctionsCalculateNowCommand>
                            </dx:SRFunctionsCalculateNowCommand>
                            <dx:SRFunctionsCalculateSheetCommand>
                            </dx:SRFunctionsCalculateSheetCommand>
                        </Items>
                    </dx:SRCalculationGroup>
                </Groups>
            </dx:SRFormulasTab>
            <dx:SRDataTab>
                <Groups>
                    <dx:SRDataSortAndFilterGroup>
                        <Items>
                            <dx:SRDataSortAscendingCommand>
                            </dx:SRDataSortAscendingCommand>
                            <dx:SRDataSortDescendingCommand>
                            </dx:SRDataSortDescendingCommand>
                            <dx:SRDataFilterToggleCommand ShowText="True">
                            </dx:SRDataFilterToggleCommand>
                            <dx:SRDataFilterClearCommand>
                            </dx:SRDataFilterClearCommand>
                            <dx:SRDataFilterReApplyCommand>
                            </dx:SRDataFilterReApplyCommand>
                        </Items>
                    </dx:SRDataSortAndFilterGroup>
                    <dx:SRDataToolsGroup>
                        <Items>
                            <dx:SRDataToolsDataValidationGroupCommand>
                            </dx:SRDataToolsDataValidationGroupCommand>
                        </Items>
                    </dx:SRDataToolsGroup>
                </Groups>
            </dx:SRDataTab>
            <dx:SRViewTab>
                <Groups>
                    <dx:SRShowGroup>
                        <Items>
                            <dx:SRViewShowGridlinesCommand>
                            </dx:SRViewShowGridlinesCommand>
                            <dx:SRViewShowHeadingsCommand>
                            </dx:SRViewShowHeadingsCommand>
                        </Items>
                    </dx:SRShowGroup>
                    <dx:SRWindowGroup>
                        <Items>
                            <dx:SRViewFreezePanesGroupCommand>
                            </dx:SRViewFreezePanesGroupCommand>
                        </Items>
                    </dx:SRWindowGroup>
                </Groups>
            </dx:SRViewTab>
        </Tabs>
        <ContextTabCategories>
            <dx:SRTableToolsContextTabCategory Color="255, 192, 0">
                <Tabs>
                    <dx:SRTableDesignContextTab>
                        <Groups>
                            <dx:SRTablePropertiesGroup>
                                <Items>
                                    <dx:SRRenameTableCommand Text="Table Name">
                                    </dx:SRRenameTableCommand>
                                </Items>
                            </dx:SRTablePropertiesGroup>
                            <dx:SRTableToolsGroup>
                                <Items>
                                    <dx:SRConvertToRangeCommand>
                                    </dx:SRConvertToRangeCommand>
                                </Items>
                            </dx:SRTableToolsGroup>
                            <dx:SRTableStyleOptionsGroup>
                                <Items>
                                    <dx:SRToggleHeaderRowCommand>
                                    </dx:SRToggleHeaderRowCommand>
                                    <dx:SRToggleTotalRowCommand>
                                    </dx:SRToggleTotalRowCommand>
                                    <dx:SRToggleBandedColumnsCommand>
                                    </dx:SRToggleBandedColumnsCommand>
                                    <dx:SRToggleFirstColumnCommand>
                                    </dx:SRToggleFirstColumnCommand>
                                    <dx:SRToggleLastColumnCommand>
                                    </dx:SRToggleLastColumnCommand>
                                    <dx:SRToggleBandedRowsCommand>
                                    </dx:SRToggleBandedRowsCommand>
                                </Items>
                            </dx:SRTableStyleOptionsGroup>
                            <dx:SRTableStyleGroup>
                                <Items>
                                    <dx:SRModifyTableStyleCommand>
                                    </dx:SRModifyTableStyleCommand>
                                </Items>
                            </dx:SRTableStyleGroup>
                        </Groups>
                    </dx:SRTableDesignContextTab>
                </Tabs>
            </dx:SRTableToolsContextTabCategory>
            <dx:SRPictureToolsContextTabCategory Color="211, 19, 19">
                <Tabs>
                    <dx:SRPictureFormatContextTab>
                        <Groups>
                            <dx:SRPictureArrangeGroup>
                                <Items>
                                    <dx:SRArrangeBringForwardGroupCommand>
                                    </dx:SRArrangeBringForwardGroupCommand>
                                    <dx:SRArrangeSendBackwardGroupCommand>
                                    </dx:SRArrangeSendBackwardGroupCommand>
                                </Items>
                            </dx:SRPictureArrangeGroup>
                        </Groups>
                    </dx:SRPictureFormatContextTab>
                </Tabs>
            </dx:SRPictureToolsContextTabCategory>
            <dx:SRChartToolsContextTabCategory Color="23, 163, 0">
                <Tabs>
                    <dx:SRChartDesignContextTab>
                        <Groups>
                            <dx:SRChartTypeGroup>
                                <Items>
                                    <dx:SRChangeChartTypeCommand>
                                    </dx:SRChangeChartTypeCommand>
                                </Items>
                            </dx:SRChartTypeGroup>
                            <dx:SRChartDataGroup>
                                <Items>
                                    <dx:SRChartSwitchRowColumnCommand>
                                    </dx:SRChartSwitchRowColumnCommand>
                                    <dx:SRChartSelectDataCommand>
                                    </dx:SRChartSelectDataCommand>
                                </Items>
                            </dx:SRChartDataGroup>
                        </Groups>
                    </dx:SRChartDesignContextTab>
                    <dx:SRChartLayoutContextTab>
                        <Groups>
                            <dx:SRChartLabelsGroup>
                                <Items>
                                    <dx:SRChartTitleCommand>
                                    </dx:SRChartTitleCommand>
                                    <dx:SRChartAxisTitlesCommand>
                                    </dx:SRChartAxisTitlesCommand>
                                    <dx:SRChartLegendCommand>
                                    </dx:SRChartLegendCommand>
                                    <dx:SRChartDataLabelsCommand>
                                    </dx:SRChartDataLabelsCommand>
                                </Items>
                            </dx:SRChartLabelsGroup>
                            <dx:SRChartAxesGroup>
                                <Items>
                                    <dx:SRChartAxesCommand>
                                    </dx:SRChartAxesCommand>
                                    <dx:SRChartGridlinesCommand>
                                    </dx:SRChartGridlinesCommand>
                                </Items>
                            </dx:SRChartAxesGroup>
                        </Groups>
                    </dx:SRChartLayoutContextTab>
                    <dx:SRChartFormatContextTab>
                        <Groups>
                            <dx:SRChartArrangeGroup>
                                <Items>
                                    <dx:SRArrangeBringForwardGroupCommand>
                                    </dx:SRArrangeBringForwardGroupCommand>
                                    <dx:SRArrangeSendBackwardGroupCommand>
                                    </dx:SRArrangeSendBackwardGroupCommand>
                                </Items>
                            </dx:SRChartArrangeGroup>
                        </Groups>
                    </dx:SRChartFormatContextTab>
                </Tabs>
            </dx:SRChartToolsContextTabCategory>
        </ContextTabCategories>
        <ClientSideEvents CommandExecuted="function(s, e) {
             App.onDocumentRibbonCommandExecuted(e.item.name, 'worksheet');
         }" />
    </dx:ASPxRibbon>
    <dx:ASPxSpreadsheet ID="Spreadsheet" ClientInstanceName="spreadsheet" runat="server" Width="100%" Height="700px"
        ActiveTabIndex="0" ShowConfirmOnLosingChanges="false" AssociatedRibbonID="DocumentRibbon" RibbonMode="ExternalRibbon"
        AutoSaveMode="On" AutoSaveTimeout="00:01:00" OnInit="Spreadsheet_Init">
        <ClientSideEvents Init="App.onDocumentEditorInit" 
            DocumentChanged="App.onDocumentEditorDocumentChanged" 
            BeginSynchronization="App.onDocumentEditorBeginSynchronization" 
            EndSynchronization="App.onDocumentEditorEndSynchronization" 
            BeginCallback="App.onControlBeginCallback" 
            EndCallback="App.onControlEndCallback" />
    </dx:ASPxSpreadsheet>
</asp:Content>
